# Word Games: Mad Libs

print()
print('Please enter the following: \n')
adjective = input('adjective: ')
animal = input('animal: ')
verb1 = input('verb: ')
exclamation1 = input('exclamation: ')
verb2 = input('verb: ')
verb3 = input('verb: ')
verb4 = input('past tense verb: ')
name1 = input("a person's name: ")
verb5 = input('verb: ')
exclamation2 = input('exclamation: ')
name2 = input("a person's name: ")
print()
print('Your story is: \n')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective.lower()} {animal.lower()} {verb1.lower()} down the hallway. "{exclamation1.capitalize()}!" I yelled. But all I could think to do was to {verb2.lower()} over and over. Miraculously, that caused it to stop, but not before it tried to {verb3.lower()} right in front of my family.')
print(f"We all {verb4.lower()} home with the day's events still on our minds. {name1.capitalize()} was still traumatized for several months. They would {verb5.lower()} up from their sleep and scream '{exclamation2.upper()}' until {name2.capitalize()} went in to calm them down. Even I still think about the {animal.lower()} incident from time to time.")
